# LandingOS — production Docker image.
#
# Multi-stage build:
#   1) deps    — install node_modules (cached layer)
#   2) builder — prisma generate + next build → standalone output
#   3) runner  — slim runtime: standalone server + static assets + prisma client
#
# Persistence: NOTHING durable lives inside this image. The database is an
# external Postgres (Neon) reached via a runtime DATABASE_URL, and uploaded
# images go to Cloudflare R2. That combination is what lets the app run on a
# host with a purely ephemeral filesystem — such as the Render free tier, which
# wipes the container on every deploy and every idle spin-down.
#
# /app/data still exists as a local fallback for uploads when R2 is not
# configured (useful for self-hosting with a mounted volume), but on Render it
# is scratch space and its contents are expected to disappear.

# ---------- 1) deps ----------
FROM node:22-alpine AS deps
WORKDIR /app

# OpenSSL is required by Prisma's native query engine on Alpine.
RUN apk add --no-cache libc6-compat openssl

# Pin npm rather than trusting whatever the base image bundles. `node:22-alpine`
# is a moving tag, so its npm changes under us — and npm versions disagree about
# optional peer dependencies, which decides whether package-lock.json is
# considered in sync at all.
#
# This is not hypothetical: the lockfile was generated by npm 11, which omits a
# nested @swc/helpers copy that npm 10 insists on (next pins the hoisted one to
# 0.5.15 while a transitive peer wants >=0.5.17). npm ci then failed the build
# with "Missing: @swc/helpers@0.5.23 from lock file" while installing fine
# locally. Pinning makes the build reproducible instead of dependent on when it
# last pulled the base image.
#
# If you regenerate package-lock.json, use THIS version so the two stay aligned:
#   npx npm@10.9.4 install --package-lock-only
RUN npm i -g npm@10.9.4

COPY package.json package-lock.json* ./
COPY prisma ./prisma
RUN npm ci

# ---------- 2) builder ----------
FROM node:22-alpine AS builder
WORKDIR /app
RUN apk add --no-cache libc6-compat openssl

COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Build-time env. AUTH_SECRET can be overridden at runtime; we set a build-time
# placeholder so the build doesn't hard-fail, but the real secret MUST be
# provided as a runtime env var on the host.
ENV NEXT_TELEMETRY_DISABLED=1
# Placeholder only. `prisma generate` and `next build` never open a connection,
# but Prisma validates that the URL scheme matches the datasource provider — so
# this has to be a postgresql:// string, not a file: one. Nothing connects here.
ENV DATABASE_URL="postgresql://placeholder:placeholder@localhost:5432/placeholder"
ENV AUTH_SECRET="build-time-placeholder-change-at-runtime"

# Generate the Prisma client, then build the standalone Next.js bundle.
RUN npx prisma generate
RUN npm run build

# ---------- 3) runner ----------
FROM node:22-alpine AS runner
WORKDIR /app
RUN apk add --no-cache libc6-compat openssl

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=3000
ENV HOSTNAME=0.0.0.0

# Non-root user for security.
RUN addgroup --system --gid 1001 nodejs \
 && adduser  --system --uid 1001 nextjs

# Create the persistent data directory, owned by the runtime user. Mount a
# volume here on the host. Without the chown, the container fails at startup
# with "unable to open database file" since it runs as nextjs, not root.
RUN mkdir -p /app/data && chown -R nextjs:nodejs /app/data

# --- Standalone server bundle ---
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
# --- Static assets Next.js does NOT bundle into standalone ---
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
# --- Public assets (logo, avatars, products) + uploads dir ---
COPY --from=builder --chown=nextjs:nodejs /app/public ./public
# --- Prisma schema + seed scripts (needed at startup) ---
COPY --from=builder --chown=nextjs:nodejs /app/prisma ./prisma
# --- Source needed by seed scripts (they import from ../src/lib/db) ---
COPY --from=builder --chown=nextjs:nodejs /app/src/lib ./src/lib
COPY --from=builder --chown=nextjs:nodejs /app/tsconfig.json ./tsconfig.json
# --- Full node_modules so tsx + prisma client are available at runtime ---
COPY --from=builder --chown=nextjs:nodejs /app/node_modules ./node_modules
COPY --chown=nextjs:nodejs package.json ./

# DATABASE_URL is deliberately NOT set here. It must come from the host at
# runtime (Render → Environment) pointing at the external Postgres. Baking a
# default in would be worse than having none: a forgotten host variable would
# silently fall back to a throwaway database instead of failing, and the
# entrypoint would happily seed a fresh store over an empty schema. The
# entrypoint refuses to start without it.

# Entrypoint: verify config, push schema, seed admin/themes/wilayas
# (idempotent), seed demo data, then start the server.
COPY --chown=nextjs:nodejs docker-entrypoint.sh /app/docker-entrypoint.sh
RUN chmod +x /app/docker-entrypoint.sh

USER nextjs
EXPOSE 3000

CMD ["/app/docker-entrypoint.sh"]
